import type { Logger } from '@guiiai/logg';
import { generateText } from 'xsai';

import { mergeContext } from './merge';
import { renderSystemPrompt } from './prompt';
import { createSendMessageTool } from './tools';
import type { DriverConfig, TurnResponse } from './types';
import type { DB } from '../db/client';
import { loadTurnResponses, persistTurnResponse } from '../db/persistence';
import type { RenderedContext } from '../rendering/types';

export { mergeContext } from './merge';
export { renderSystemPrompt } from './prompt';
export type { DriverConfig, TurnResponse } from './types';

const DEBOUNCE_MS = 2000;
const MAX_STEPS = 5;

export const createDriver = (config: DriverConfig, deps: {
  db: DB;
  sendMessage: (chatId: string, text: string, replyToMessageId?: number) => Promise<void>;
  logger: Logger;
}) => {
  const { db, logger } = deps;
  const log = logger.withContext('driver');
  const chatIds = new Set(config.chatIds);
  const timers = new Map<string, ReturnType<typeof setTimeout>>();

  // The latest RC per chat, updated by handleEvent
  const latestRC = new Map<string, RenderedContext>();

  const triggerLLMCall = async (chatId: string) => {
    const rc = latestRC.get(chatId);
    if (!rc || rc.length === 0) return;

    log.withFields({ chatId }).log('Triggering LLM call');

    // Load existing TRs
    const trRows = loadTurnResponses(db, chatId);
    const trs: TurnResponse[] = trRows.map(r => ({
      requestedAtMs: r.requestedAt,
      provider: r.provider,
      data: r.data,
      sessionMeta: r.sessionMeta,
      inputTokens: r.inputTokens,
      outputTokens: r.outputTokens,
    }));

    // Merge RC + TRs into messages
    const messages = mergeContext(rc, trs);
    if (messages.length === 0) return;

    // Render system prompt
    const system = await renderSystemPrompt({
      currentChannel: 'telegram',
      timeNow: new Date().toISOString(),
    });

    // Create send_message tool
    const sendMessageTool = createSendMessageTool(async (text, replyTo) => {
      log.withFields({ chatId, text: text.length > 100 ? `${text.slice(0, 100)}...` : text, replyTo }).log('send_message tool called');
      await deps.sendMessage(chatId, text, replyTo ? Number(replyTo) : undefined);
    });

    const requestedAtMs = Date.now();

    try {
      const result = await generateText({
        baseURL: config.apiBaseUrl,
        apiKey: config.apiKey,
        model: config.model,
        messages,
        system,
        tools: [sendMessageTool],
        maxSteps: MAX_STEPS,
      });

      log.withFields({
        chatId,
        finishReason: result.finishReason,
        text: result.text?.slice(0, 200),
        steps: result.steps.length,
        usage: result.usage,
      }).log('LLM call completed');

      // Extract TR data from result: the new messages generated by the LLM
      // result.messages contains the full conversation including our input;
      // we only want the new messages (after our input)
      const newMessages = result.messages.slice(messages.length);

      if (newMessages.length > 0) {
        persistTurnResponse(db, chatId, {
          requestedAtMs,
          provider: 'openai-chat',
          data: newMessages,
          inputTokens: result.usage.prompt_tokens,
          outputTokens: result.usage.completion_tokens,
        });
      }
    } catch (err) {
      log.withError(err).error('LLM call failed');
    }
  };

  const handleEvent = (chatId: string, rc: RenderedContext) => {
    if (!chatIds.has(chatId)) return;

    latestRC.set(chatId, rc);

    // Debounce: reset timer on each event
    const existing = timers.get(chatId);
    if (existing) clearTimeout(existing);

    timers.set(chatId, setTimeout(() => {
      timers.delete(chatId);
      void triggerLLMCall(chatId);
    }, DEBOUNCE_MS));
  };

  const stop = () => {
    for (const timer of timers.values())
      clearTimeout(timer);
    timers.clear();
  };

  return { handleEvent, stop };
};
