// Auto-generated test fixtures from database analysis.
// Each fixture represents a unique structural pattern found in real data.
//
// Generated by: npx tsx src/unified-api/extract-fixtures.ts

import type { ChatCompletionsEntry } from './chat-types';
import type { ResponsesDataItem } from './responses-types';

export interface Fixture<T> {
  /** Original TR id in database */
  id: number;
  /** Structural pattern signature */
  signature: string;
  /** The TR data */
  data: T[];
}

export const chatFixtures: Fixture<ChatCompletionsEntry>[] = [
  // [TR #7] openai-chat::content:string | tool_calls:none
  {
    'id': 7,
    'signature': 'SIG_340',
    'data': [
      {
        'content': 'synthetic_text_149',
        'role': 'assistant',
      },
    ],
  },
  // [TR #34] openai-chat::content:string | tool_calls:1 → tool_content:string | rfu:number:0
  {
    'id': 34,
    'signature': 'SIG_341',
    'data': [
      {
        'content': 'synthetic_text_150',
        'role': 'assistant',
        'tool_calls': [
          {
            'function': {
              'arguments': '{"key":"value_1"}',
              'name': 'send_message',
            },
            'id': 'toolu_vrtx_01LP1rfErykf3qmuaWdvkz45',
            'type': 'function',
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01LP1rfErykf3qmuaWdvkz45',
        'content': 'synthetic_text_151',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #13460] openai-chat::content:string | tool_calls:1 → tool_content:string | rfu:boolean:false
  {
    'id': 13460,
    'signature': 'SIG_342',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_152',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01G8ykcGrCGSm8egK9J3izKb',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_2"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01G8ykcGrCGSm8egK9J3izKb',
        'content': 'synthetic_text_153',
        'requiresFollowUp': false,
      },
    ],
  },
  // [TR #39] openai-chat::content:absent | tool_calls:1 → tool_content:string | rfu:number:0
  {
    'id': 39,
    'signature': 'SIG_343',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'function': {
              'arguments': '{"key":"value_3"}',
              'name': 'send_message',
            },
            'id': 'toolu_vrtx_013i7qpf3Cp3rUJHRppJ9Q4o',
            'type': 'function',
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_013i7qpf3Cp3rUJHRppJ9Q4o',
        'content': 'synthetic_text_154',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #13465] openai-chat::content:absent | tool_calls:1 → tool_content:string | rfu:boolean:false
  {
    'id': 13465,
    'signature': 'SIG_344',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01Xw9HxkTXGSGJudRB8B8wfy',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_4"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01Xw9HxkTXGSGJudRB8B8wfy',
        'content': 'synthetic_text_155',
        'requiresFollowUp': false,
      },
    ],
  },
  // [TR #7018] openai-chat::content:string | tool_calls:none | reasoning:[reasoning]
  {
    'id': 7018,
    'signature': 'SIG_345',
    'data': [
      {
        'role': 'assistant',
        'reasoning': 'synthetic_text_323',
        'content': 'synthetic_text_156',
      },
    ],
  },
  // [TR #7022] openai-chat::content:absent | tool_calls:1 | reasoning:[reasoning] → tool_content:string | rfu:number:0
  {
    'id': 7022,
    'signature': 'SIG_346',
    'data': [
      {
        'role': 'assistant',
        'reasoning': 'synthetic_text_324',
        'tool_calls': [
          {
            'id': 'chatcmpl-tool-85f5697691557581',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_5"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-85f5697691557581',
        'content': 'synthetic_text_157',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #5521] openai-chat::content:absent | tool_calls:1 → tool_content:string | rfu:number:1
  {
    'id': 5521,
    'signature': 'SIG_347',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_bdrk_01894ZnP66afcPfXvLqggtGs',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_6"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_bdrk_01894ZnP66afcPfXvLqggtGs',
        'content': 'synthetic_text_158',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #5516] openai-chat::content:string | tool_calls:1 → tool_content:string | rfu:number:1
  {
    'id': 5516,
    'signature': 'SIG_348',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_159',
        'tool_calls': [
          {
            'id': 'toolu_bdrk_016yGasPHpQZ9FavyaK1Gd6x',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_7"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_bdrk_016yGasPHpQZ9FavyaK1Gd6x',
        'content': 'synthetic_text_160',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #13750] openai-chat::content:absent | tool_calls:1 → tool_content:string | rfu:boolean:true
  {
    'id': 13750,
    'signature': 'SIG_349',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01SGrj8WXzE433umYEbcuzUS',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_8"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01SGrj8WXzE433umYEbcuzUS',
        'content': 'synthetic_text_161',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #13462] openai-chat::content:string | tool_calls:1 → tool_content:string | rfu:boolean:true
  {
    'id': 13462,
    'signature': 'SIG_350',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_162',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01Eus8skSbaB4HxtmS4iFbhi',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_9"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01Eus8skSbaB4HxtmS4iFbhi',
        'content': 'synthetic_text_163',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #527] openai-chat::content:null | tool_calls:1 → tool_content:string | rfu:number:0
  {
    'id': 527,
    'signature': 'SIG_351',
    'data': [
      {
        'role': 'assistant',
        'content': null,
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01EhtEjNvW5vb8tkfgGs8AFq',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_10"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01EhtEjNvW5vb8tkfgGs8AFq',
        'content': 'synthetic_text_164',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #13741] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
  {
    'id': 13741,
    'signature': 'SIG_352',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01Ezmre15VYmwushQqete2wJ',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_11"}',
            },
          },
          {
            'id': 'toolu_vrtx_01R6k37616A6ozPkpp3Tdwp6',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_12"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01Ezmre15VYmwushQqete2wJ',
        'content': 'synthetic_text_165',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01R6k37616A6ozPkpp3Tdwp6',
        'content': 'synthetic_text_166',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #13493] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
  {
    'id': 13493,
    'signature': 'SIG_353',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_167',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01Dmzg6CS2N9JbwiKDuLm9iu',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_13"}',
            },
          },
          {
            'id': 'toolu_vrtx_019fdcozS33gaS85PvyzhsJN',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_14"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01Dmzg6CS2N9JbwiKDuLm9iu',
        'content': 'synthetic_text_168',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_019fdcozS33gaS85PvyzhsJN',
        'content': 'synthetic_text_169',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #1082] openai-chat::content:absent | tool_calls:1 | reasoning:[reasoning_opaque] → tool_content:string | rfu:number:0
  {
    'id': 1082,
    'signature': 'SIG_354',
    'data': [
      {
        'role': 'assistant',
        'reasoning_opaque': 'OPAQUE_314',
        'tool_calls': [
          {
            'id': 'call_MHxtSlhXRUlYckplcjBnM093ejQ',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_15"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'call_MHxtSlhXRUlYckplcjBnM093ejQ',
        'content': 'synthetic_text_170',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #6034] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
  {
    'id': 6034,
    'signature': 'SIG_355',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_171',
        'tool_calls': [
          {
            'id': 'toolu_01AnAT7AJY7WJAtrnLbYUfFr',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_16"}',
            },
          },
          {
            'id': 'toolu_01FxkS82PE8YQTjPZuyXWeJ2',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_17"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01AnAT7AJY7WJAtrnLbYUfFr',
        'content': 'synthetic_text_172',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01FxkS82PE8YQTjPZuyXWeJ2',
        'content': 'synthetic_text_173',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #1] openai-chat::
  {
    'id': 1,
    'signature': 'SIG_356',
    'data': [],
  },
  // [TR #7789] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
  {
    'id': 7789,
    'signature': 'SIG_357',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_bdrk_01Coxcmvf8KJmEs6oc5srejv',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_18"}',
            },
          },
          {
            'id': 'toolu_bdrk_01LsT4KHKtQYzqMWqbdW5EaQ',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_19"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_bdrk_01Coxcmvf8KJmEs6oc5srejv',
        'content': 'synthetic_text_174',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_bdrk_01LsT4KHKtQYzqMWqbdW5EaQ',
        'content': 'synthetic_text_175',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #6313] openai-chat::content:absent | tool_calls:none
  {
    'id': 6313,
    'signature': 'SIG_358',
    'data': [
      {
        'role': 'assistant',
      },
    ],
  },
  // [TR #7025] openai-chat::content:absent | tool_calls:2 | reasoning:[reasoning] → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
  {
    'id': 7025,
    'signature': 'SIG_359',
    'data': [
      {
        'role': 'assistant',
        'reasoning': 'synthetic_text_325',
        'tool_calls': [
          {
            'id': 'chatcmpl-tool-ba8c8e149a99985e',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_20"}',
            },
          },
          {
            'id': 'chatcmpl-tool-80e924ef5fb421a1',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_21"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-ba8c8e149a99985e',
        'content': 'synthetic_text_176',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-80e924ef5fb421a1',
        'content': 'synthetic_text_177',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #15765] openai-chat::content:string | tool_calls:none | reasoning:[reasoning_content]
  {
    'id': 15765,
    'signature': 'SIG_360',
    'data': [
      {
        'role': 'assistant',
        'reasoning_content': 'synthetic_text_317',
        'content': 'synthetic_text_178',
      },
    ],
  },
  // [TR #7077] openai-chat::content:string | tool_calls:1 | reasoning:[reasoning] → tool_content:string | rfu:number:0
  {
    'id': 7077,
    'signature': 'SIG_361',
    'data': [
      {
        'role': 'assistant',
        'reasoning': 'synthetic_text_326',
        'content': 'synthetic_text_179',
        'tool_calls': [
          {
            'id': 'chatcmpl-tool-a0785ab401ba3c0f',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_22"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-a0785ab401ba3c0f',
        'content': 'synthetic_text_180',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #15769] openai-chat::content:absent | tool_calls:1 | reasoning:[reasoning_content] → tool_content:string | rfu:boolean:false
  {
    'id': 15769,
    'signature': 'SIG_362',
    'data': [
      {
        'role': 'assistant',
        'reasoning_content': 'synthetic_text_318',
        'tool_calls': [
          {
            'id': 'send_message:103',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_23"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'send_message:103',
        'content': 'synthetic_text_181',
        'requiresFollowUp': false,
      },
    ],
  },
  // [TR #13644] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:boolean:false → tool_content:string | rfu:boolean:false
  {
    'id': 13644,
    'signature': 'SIG_363',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_182',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01QYaEwGCWHFsaCYaxEWEwzi',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_24"}',
            },
          },
          {
            'id': 'toolu_vrtx_01KFLrsuAeneK9gibQPipvhF',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_25"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01QYaEwGCWHFsaCYaxEWEwzi',
        'content': 'synthetic_text_183',
        'requiresFollowUp': false,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01KFLrsuAeneK9gibQPipvhF',
        'content': 'synthetic_text_184',
        'requiresFollowUp': false,
      },
    ],
  },
  // [TR #13636] openai-chat::content:absent | tool_calls:3 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
  {
    'id': 13636,
    'signature': 'SIG_364',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01JT6RzXzUzSvfAfMHAXbaCn',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_26"}',
            },
          },
          {
            'id': 'toolu_vrtx_01RxfShXaGviuXWhWaYehoM7',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_27"}',
            },
          },
          {
            'id': 'toolu_vrtx_01Hb59XFrj88X5tV3LSWZLjo',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_28"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01JT6RzXzUzSvfAfMHAXbaCn',
        'content': 'synthetic_text_185',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01RxfShXaGviuXWhWaYehoM7',
        'content': 'synthetic_text_186',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01Hb59XFrj88X5tV3LSWZLjo',
        'content': 'synthetic_text_187',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #16262] openai-chat::content:string | tool_calls:1 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true
  {
    'id': 16262,
    'signature': 'SIG_365',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_188',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_014rc5VaVFVqkravNFj4miZx',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_29"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_014rc5VaVFVqkravNFj4miZx',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #6543] openai-chat::content:string | tool_calls:3 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
  {
    'id': 6543,
    'signature': 'SIG_366',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_189',
        'tool_calls': [
          {
            'id': 'toolu_bdrk_013ULhH5SDBKURkCBJeJ7xC1',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_30"}',
            },
          },
          {
            'id': 'toolu_bdrk_01AXc1wVSpScqqS6N1tzXdyR',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_31"}',
            },
          },
          {
            'id': 'toolu_bdrk_018cHNEK3jf5ks1L1iT4VTw5',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_32"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_bdrk_013ULhH5SDBKURkCBJeJ7xC1',
        'content': 'synthetic_text_190',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_bdrk_01AXc1wVSpScqqS6N1tzXdyR',
        'content': 'synthetic_text_191',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_bdrk_018cHNEK3jf5ks1L1iT4VTw5',
        'content': 'synthetic_text_192',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #7019] openai-chat::content:absent | tool_calls:none | reasoning:[reasoning]
  {
    'id': 7019,
    'signature': 'SIG_367',
    'data': [
      {
        'role': 'assistant',
        'reasoning': 'synthetic_text_327',
      },
    ],
  },
  // [TR #7668] openai-chat::content:absent | tool_calls:3 | reasoning:[reasoning] → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
  {
    'id': 7668,
    'signature': 'SIG_368',
    'data': [
      {
        'role': 'assistant',
        'reasoning': 'synthetic_text_328',
        'tool_calls': [
          {
            'id': 'chatcmpl-tool-8fdf272ad34c9799',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_33"}',
            },
          },
          {
            'id': 'chatcmpl-tool-8980801fa3c7edc8',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_34"}',
            },
          },
          {
            'id': 'chatcmpl-tool-bc032763339c0b2c',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_35"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-8fdf272ad34c9799',
        'content': 'synthetic_text_193',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-8980801fa3c7edc8',
        'content': 'synthetic_text_194',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-bc032763339c0b2c',
        'content': 'synthetic_text_195',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #6090] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
  {
    'id': 6090,
    'signature': 'SIG_369',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_bdrk_01UMuNkd6aKEyYMq3MtWSehK',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_36"}',
            },
          },
          {
            'id': 'toolu_bdrk_01E9N4H8yGz6rDJ6FWfj3c3u',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_37"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_bdrk_01UMuNkd6aKEyYMq3MtWSehK',
        'content': 'synthetic_text_196',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_bdrk_01E9N4H8yGz6rDJ6FWfj3c3u',
        'content': 'synthetic_text_197',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #9407] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1
  {
    'id': 9407,
    'signature': 'SIG_370',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01SLAtkoxeKr9KCt6VutbUz8',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_38"}',
            },
          },
          {
            'id': 'toolu_vrtx_013NGYBerbSf129teFnR4j8y',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_39"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01SLAtkoxeKr9KCt6VutbUz8',
        'content': 'synthetic_text_198',
        'requiresFollowUp': 0,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_013NGYBerbSf129teFnR4j8y',
        'content': 'synthetic_text_199',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #6340] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1
  {
    'id': 6340,
    'signature': 'SIG_371',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_200',
        'tool_calls': [
          {
            'id': 'toolu_0135AGceAkMqWQPUzCu5oaLq',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_40"}',
            },
          },
          {
            'id': 'toolu_01V7kt8EAwgn33SWio9A1Kh4',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_41"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_0135AGceAkMqWQPUzCu5oaLq',
        'content': 'synthetic_text_201',
        'requiresFollowUp': 0,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01V7kt8EAwgn33SWio9A1Kh4',
        'content': 'synthetic_text_202',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #7069] openai-chat::content:absent | tool_calls:1 | reasoning:[reasoning] → tool_content:string | rfu:number:1
  {
    'id': 7069,
    'signature': 'SIG_372',
    'data': [
      {
        'role': 'assistant',
        'reasoning': 'synthetic_text_329',
        'tool_calls': [
          {
            'id': 'chatcmpl-tool-b2f1582e44c7fd03',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_42"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-b2f1582e44c7fd03',
        'content': 'synthetic_text_203',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #8117] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
  {
    'id': 8117,
    'signature': 'SIG_373',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_204',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01LoWy2JrPUtdp3RBCEUBMNg',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_43"}',
            },
          },
          {
            'id': 'toolu_vrtx_01FCXW6kCFbcN4HPgLi96gd3',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_44"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01LoWy2JrPUtdp3RBCEUBMNg',
        'content': 'synthetic_text_205',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01FCXW6kCFbcN4HPgLi96gd3',
        'content': 'synthetic_text_206',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #10408] openai-chat::content:absent | tool_calls:3 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
  {
    'id': 10408,
    'signature': 'SIG_374',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_01EBjVu8Y5tV9q9jXf7J8rpQ',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_45"}',
            },
          },
          {
            'id': 'toolu_01U7zJs5z3TJmktZHiRbVLHm',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_46"}',
            },
          },
          {
            'id': 'toolu_01Tx95GAe1SWMn5SbL9hbvsN',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_47"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01EBjVu8Y5tV9q9jXf7J8rpQ',
        'content': 'synthetic_text_207',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01U7zJs5z3TJmktZHiRbVLHm',
        'content': 'synthetic_text_208',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01Tx95GAe1SWMn5SbL9hbvsN',
        'content': 'synthetic_text_209',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #14752] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:boolean:false → tool_content:string | rfu:boolean:true
  {
    'id': 14752,
    'signature': 'SIG_375',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_210',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01Ka4tsh99oTHBgWt3sxKYLg',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_48"}',
            },
          },
          {
            'id': 'toolu_vrtx_019jUGBE8w1g9PKwrCJfEnSS',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_49"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01Ka4tsh99oTHBgWt3sxKYLg',
        'content': 'synthetic_text_211',
        'requiresFollowUp': false,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_019jUGBE8w1g9PKwrCJfEnSS',
        'content': 'synthetic_text_212',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #33] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:0
  {
    'id': 33,
    'signature': 'SIG_376',
    'data': [
      {
        'content': 'synthetic_text_213',
        'role': 'assistant',
        'tool_calls': [
          {
            'function': {
              'arguments': '{"key":"value_50"}',
              'name': 'send_message',
            },
            'id': 'toolu_vrtx_01SgZtFWLZgf7STP1pmYG3US',
            'type': 'function',
          },
          {
            'function': {
              'arguments': '{"key":"value_51"}',
              'name': 'send_message',
            },
            'id': 'toolu_vrtx_017i5zCVZP6KxnMqbM4EKpnt',
            'type': 'function',
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01SgZtFWLZgf7STP1pmYG3US',
        'content': 'synthetic_text_214',
        'requiresFollowUp': 0,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_017i5zCVZP6KxnMqbM4EKpnt',
        'content': 'synthetic_text_215',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #8197] openai-chat::content:absent | tool_calls:3 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
  {
    'id': 8197,
    'signature': 'SIG_377',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01L7h83739AeDv8BZEzL8cu1',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_52"}',
            },
          },
          {
            'id': 'toolu_vrtx_01GoP1igH3PCnuMFURRtyFyU',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_53"}',
            },
          },
          {
            'id': 'toolu_vrtx_014yGMVKYWYuXUgJNAZTfvbm',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_54"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01L7h83739AeDv8BZEzL8cu1',
        'content': 'synthetic_text_216',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01GoP1igH3PCnuMFURRtyFyU',
        'content': 'synthetic_text_217',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_014yGMVKYWYuXUgJNAZTfvbm',
        'content': 'synthetic_text_218',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #16] openai-chat::content:string | tool_calls:none | reasoning:[reasoning_opaque]
  {
    'id': 16,
    'signature': 'SIG_378',
    'data': [
      {
        'content': 'synthetic_text_219',
        'reasoning_opaque': 'OPAQUE_315',
        'role': 'assistant',
      },
    ],
  },
  // [TR #13459] openai-chat::content:string | tool_calls:4 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
  {
    'id': 13459,
    'signature': 'SIG_379',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_220',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01BmzDBRyuzGKdeoDAsmGEv7',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_55"}',
            },
          },
          {
            'id': 'toolu_vrtx_017DtBQSw38aqNmWjwiXLZuB',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_56"}',
            },
          },
          {
            'id': 'toolu_vrtx_01VG5qmwTyBkHZhxBsbWEY7P',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_57"}',
            },
          },
          {
            'id': 'toolu_vrtx_01H8FUTdk9BMSdan3WLSTert',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_58"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01BmzDBRyuzGKdeoDAsmGEv7',
        'content': 'synthetic_text_221',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_017DtBQSw38aqNmWjwiXLZuB',
        'content': 'synthetic_text_222',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01VG5qmwTyBkHZhxBsbWEY7P',
        'content': 'synthetic_text_223',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01H8FUTdk9BMSdan3WLSTert',
        'content': 'synthetic_text_224',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #18381] openai-chat::content:string | tool_calls:3 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
  {
    'id': 18381,
    'signature': 'SIG_380',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_225',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_011LEFknvt3iadfyHsvoaPdj',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_59"}',
            },
          },
          {
            'id': 'toolu_vrtx_01WSps8PdDz4Q1sZRySpXzPq',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_60"}',
            },
          },
          {
            'id': 'toolu_vrtx_01Vfea49eENiMBJyg64ZPXN6',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_61"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_011LEFknvt3iadfyHsvoaPdj',
        'content': 'synthetic_text_226',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01WSps8PdDz4Q1sZRySpXzPq',
        'content': 'synthetic_text_227',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01Vfea49eENiMBJyg64ZPXN6',
        'content': 'synthetic_text_228',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #7686] openai-chat::content:absent | tool_calls:2 | reasoning:[reasoning] → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
  {
    'id': 7686,
    'signature': 'SIG_381',
    'data': [
      {
        'role': 'assistant',
        'reasoning': 'synthetic_text_330',
        'tool_calls': [
          {
            'id': 'chatcmpl-tool-bc133d4536470805',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_62"}',
            },
          },
          {
            'id': 'chatcmpl-tool-b1f3ca0ff7fdb1b7',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_63"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-bc133d4536470805',
        'content': 'synthetic_text_229',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-b1f3ca0ff7fdb1b7',
        'content': 'synthetic_text_230',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #8114] openai-chat::content:string | tool_calls:3 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
  {
    'id': 8114,
    'signature': 'SIG_382',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_231',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_011AnPYwMKfSyV5kse6FmbJW',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_64"}',
            },
          },
          {
            'id': 'toolu_vrtx_01VBdxuXUQrKx7x92NTDagWv',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_65"}',
            },
          },
          {
            'id': 'toolu_vrtx_01MTuRGEyiu4X63PfVHz6Prx',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_66"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_011AnPYwMKfSyV5kse6FmbJW',
        'content': 'synthetic_text_232',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01VBdxuXUQrKx7x92NTDagWv',
        'content': 'synthetic_text_233',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01MTuRGEyiu4X63PfVHz6Prx',
        'content': 'synthetic_text_234',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #14031] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:boolean:false → tool_content:string | rfu:boolean:false
  {
    'id': 14031,
    'signature': 'SIG_383',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01EqEc9X1YZSXp9Kqkwx5QDY',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_67"}',
            },
          },
          {
            'id': 'toolu_vrtx_01ECnzyAYZn89zD9oASKHgf9',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_68"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01EqEc9X1YZSXp9Kqkwx5QDY',
        'content': 'synthetic_text_235',
        'requiresFollowUp': false,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01ECnzyAYZn89zD9oASKHgf9',
        'content': 'synthetic_text_236',
        'requiresFollowUp': false,
      },
    ],
  },
  // [TR #16418] openai-chat::content:absent | tool_calls:1 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true
  {
    'id': 16418,
    'signature': 'SIG_384',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01RJLVKY62oaPTMixzNHv1Wp',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_69"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01RJLVKY62oaPTMixzNHv1Wp',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #17] openai-chat::content:absent | tool_calls:1 | extra:[padding] → tool_content:string | rfu:number:0 → content:empty-string | tool_calls:none | extra:[padding]
  {
    'id': 17,
    'signature': 'SIG_385',
    'data': [
      {
        'padding': 'PAD_334',
        'role': 'assistant',
        'tool_calls': [
          {
            'function': {
              'arguments': '{"key":"value_70"}',
              'name': 'send_message',
            },
            'id': 'call_HZy1Lv530rcDgYo3ZxurqUrk',
            'type': 'function',
          },
        ],
      },
      {
        'content': 'synthetic_text_237',
        'role': 'tool',
        'tool_call_id': 'call_HZy1Lv530rcDgYo3ZxurqUrk',
        'requiresFollowUp': 0,
      },
      {
        'content': '',
        'padding': 'PAD_335',
        'role': 'assistant',
      },
    ],
  },
  // [TR #11471] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:0
  {
    'id': 11471,
    'signature': 'SIG_386',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01RioxhVVzKXmeaZz3ZNzF2R',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_71"}',
            },
          },
          {
            'id': 'toolu_vrtx_01TWE2GwukHqNwYegSEEPkmt',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_72"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01RioxhVVzKXmeaZz3ZNzF2R',
        'content': 'synthetic_text_238',
        'requiresFollowUp': 0,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01TWE2GwukHqNwYegSEEPkmt',
        'content': 'synthetic_text_239',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #13461] openai-chat::content:string | tool_calls:2 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:false
  {
    'id': 13461,
    'signature': 'SIG_387',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_240',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01646XWEEdby1FyBLtwEdQy4',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_73"}',
            },
          },
          {
            'id': 'toolu_vrtx_013C954fYpLWrfAUe7Jk3T4d',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_74"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01646XWEEdby1FyBLtwEdQy4',
        'content': 'synthetic_text_241',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_013C954fYpLWrfAUe7Jk3T4d',
        'content': 'synthetic_text_242',
        'requiresFollowUp': false,
      },
    ],
  },
  // [TR #16422] openai-chat::content:string | tool_calls:2 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:string | rfu:boolean:true
  {
    'id': 16422,
    'signature': 'SIG_388',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_243',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01BmxsB9CKNH6JZexp4oxjBF',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_75"}',
            },
          },
          {
            'id': 'toolu_vrtx_01NSTCFFi2E3jdneg7PcLVib',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_76"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01BmxsB9CKNH6JZexp4oxjBF',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01NSTCFFi2E3jdneg7PcLVib',
        'content': 'synthetic_text_244',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #6640] openai-chat::content:string | tool_calls:4 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
  {
    'id': 6640,
    'signature': 'SIG_389',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_245',
        'tool_calls': [
          {
            'id': 'toolu_01YY2JSBVLi5311CDsfWvJ8q',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_77"}',
            },
          },
          {
            'id': 'toolu_01CBDVeizUkZfYjV6KEVxjL6',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_78"}',
            },
          },
          {
            'id': 'toolu_01FojrEWWihmF6M84Y2pfhq1',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_79"}',
            },
          },
          {
            'id': 'toolu_01DwM9wZxZhUfsy51teA9dUc',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_80"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01YY2JSBVLi5311CDsfWvJ8q',
        'content': 'synthetic_text_246',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01CBDVeizUkZfYjV6KEVxjL6',
        'content': 'synthetic_text_247',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01FojrEWWihmF6M84Y2pfhq1',
        'content': 'synthetic_text_248',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01DwM9wZxZhUfsy51teA9dUc',
        'content': 'synthetic_text_249',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #7052] openai-chat::content:absent | tool_calls:1 | reasoning:[reasoning] | tc_malformed_args → tool_content:string | rfu:number:0
  {
    'id': 7052,
    'signature': 'SIG_390',
    'data': [
      {
        'role': 'assistant',
        'reasoning': 'synthetic_text_331',
        'tool_calls': [
          {
            'id': 'chatcmpl-tool-bddb402b15a5f2c7',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_81"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-bddb402b15a5f2c7',
        'content': 'synthetic_text_250',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #7248] openai-chat::content:absent | tool_calls:2 | reasoning:[reasoning] → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:0
  {
    'id': 7248,
    'signature': 'SIG_391',
    'data': [
      {
        'role': 'assistant',
        'reasoning': 'synthetic_text_332',
        'tool_calls': [
          {
            'id': 'chatcmpl-tool-a12c35ece8f8dbb2',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_82"}',
            },
          },
          {
            'id': 'chatcmpl-tool-abaaeaa3839b7067',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_83"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-a12c35ece8f8dbb2',
        'content': 'synthetic_text_251',
        'requiresFollowUp': 0,
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-abaaeaa3839b7067',
        'content': 'synthetic_text_252',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #15788] openai-chat::content:absent | tool_calls:none | reasoning:[reasoning_content]
  {
    'id': 15788,
    'signature': 'SIG_392',
    'data': [
      {
        'role': 'assistant',
        'reasoning_content': 'synthetic_text_319',
      },
    ],
  },
  // [TR #16046] openai-chat::content:absent | tool_calls:2 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:string | rfu:boolean:true
  {
    'id': 16046,
    'signature': 'SIG_393',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_016drYLHShKRBsLpooXEUnxW',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_84"}',
            },
          },
          {
            'id': 'toolu_vrtx_01W87aLyDnaWEqy8WngBeXvj',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_85"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_016drYLHShKRBsLpooXEUnxW',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01W87aLyDnaWEqy8WngBeXvj',
        'content': 'synthetic_text_253',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #15] openai-chat::content:empty-string | tool_calls:1 | reasoning:[reasoning_text,reasoning_opaque] | tc_extra:[index] → tool_content:string | rfu:number:0 → content:empty-string | tool_calls:none | reasoning:[reasoning_text]
  {
    'id': 15,
    'signature': 'SIG_394',
    'data': [
      {
        'content': '',
        'reasoning_opaque': 'OPAQUE_316',
        'reasoning_text': 'synthetic_text_321',
        'role': 'assistant',
        'tool_calls': [
          {
            'function': {
              'arguments': '{"key":"value_86"}',
              'name': 'send_message',
            },
            'id': 'call_MHxpNVV3OUo3ak8yT0hlaTE1bTY',
            'index': 0,
            'type': 'function',
          },
        ],
      },
      {
        'content': 'synthetic_text_254',
        'role': 'tool',
        'tool_call_id': 'call_MHxpNVV3OUo3ak8yT0hlaTE1bTY',
        'requiresFollowUp': 0,
      },
      {
        'content': '',
        'reasoning_text': 'synthetic_text_322',
        'role': 'assistant',
      },
    ],
  },
  // [TR #1735] openai-chat::content:string | tool_calls:1 | tc_malformed_args → tool_content:string | rfu:number:0
  {
    'id': 1735,
    'signature': 'SIG_395',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_255',
        'tool_calls': [
          {
            'id': 'toolu_bdrk_01JaxrxFtQgQUAMV7A52Nser',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_87"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_bdrk_01JaxrxFtQgQUAMV7A52Nser',
        'content': 'synthetic_text_256',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #7701] openai-chat::content:absent | tool_calls:4 | reasoning:[reasoning] → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:0
  {
    'id': 7701,
    'signature': 'SIG_396',
    'data': [
      {
        'role': 'assistant',
        'reasoning': 'synthetic_text_333',
        'tool_calls': [
          {
            'id': 'chatcmpl-tool-b2bdec3d7fbe8c18',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_88"}',
            },
          },
          {
            'id': 'chatcmpl-tool-b7863a852e3279ca',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_89"}',
            },
          },
          {
            'id': 'chatcmpl-tool-876820e547a0bb6e',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_90"}',
            },
          },
          {
            'id': 'chatcmpl-tool-80cebfda4c0abf0b',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_91"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-b2bdec3d7fbe8c18',
        'content': 'synthetic_text_257',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-b7863a852e3279ca',
        'content': 'synthetic_text_258',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-876820e547a0bb6e',
        'content': 'synthetic_text_259',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'chatcmpl-tool-80cebfda4c0abf0b',
        'content': 'synthetic_text_260',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #9409] openai-chat::content:string | tool_calls:6 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
  {
    'id': 9409,
    'signature': 'SIG_397',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_261',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_017AXFgSyUL3wNQN6ZDsbv5M',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_92"}',
            },
          },
          {
            'id': 'toolu_vrtx_01Hv6J2ZPPuLCh6SjRbcgy2Y',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_93"}',
            },
          },
          {
            'id': 'toolu_vrtx_01BFfRHqhCQE19Aie7i3k6h8',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_94"}',
            },
          },
          {
            'id': 'toolu_vrtx_011PwuVVcJcCxin5yus5a3Lb',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_95"}',
            },
          },
          {
            'id': 'toolu_vrtx_01X6JYLWGZKA4yx3ZtEJe6eF',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_96"}',
            },
          },
          {
            'id': 'toolu_vrtx_01BAfSbcuhMQnBdiAnjCojA2',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_97"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_017AXFgSyUL3wNQN6ZDsbv5M',
        'content': 'synthetic_text_262',
        'requiresFollowUp': 0,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01Hv6J2ZPPuLCh6SjRbcgy2Y',
        'content': 'synthetic_text_263',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01BFfRHqhCQE19Aie7i3k6h8',
        'content': 'synthetic_text_264',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_011PwuVVcJcCxin5yus5a3Lb',
        'content': 'synthetic_text_265',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01X6JYLWGZKA4yx3ZtEJe6eF',
        'content': 'synthetic_text_266',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01BAfSbcuhMQnBdiAnjCojA2',
        'content': 'synthetic_text_267',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #10094] openai-chat::content:string | tool_calls:6 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
  {
    'id': 10094,
    'signature': 'SIG_398',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_268',
        'tool_calls': [
          {
            'id': 'toolu_01ShNbYAKx25d8zaUBvFNoHJ',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_98"}',
            },
          },
          {
            'id': 'toolu_01S1SstmWt78is1bNgN5NnCw',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_99"}',
            },
          },
          {
            'id': 'toolu_01LAn147VARj4Nfz8fFGX1zt',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_100"}',
            },
          },
          {
            'id': 'toolu_01GXNrkgZtX5EVTH4DqyySmf',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_101"}',
            },
          },
          {
            'id': 'toolu_01EWVhn3mJVmL8Eh4xbdXKds',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_102"}',
            },
          },
          {
            'id': 'toolu_01AoSJ5zq15LsMcpbAByGbUS',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_103"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01ShNbYAKx25d8zaUBvFNoHJ',
        'content': 'synthetic_text_269',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01S1SstmWt78is1bNgN5NnCw',
        'content': 'synthetic_text_270',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01LAn147VARj4Nfz8fFGX1zt',
        'content': 'synthetic_text_271',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01GXNrkgZtX5EVTH4DqyySmf',
        'content': 'synthetic_text_272',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01EWVhn3mJVmL8Eh4xbdXKds',
        'content': 'synthetic_text_273',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01AoSJ5zq15LsMcpbAByGbUS',
        'content': 'synthetic_text_274',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #10095] openai-chat::content:string | tool_calls:8 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
  {
    'id': 10095,
    'signature': 'SIG_399',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_275',
        'tool_calls': [
          {
            'id': 'toolu_01UrHyYpdHtu7BDMJkwh2QRA',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_104"}',
            },
          },
          {
            'id': 'toolu_014RKws9xyBNCFH2qf253Xs3',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_105"}',
            },
          },
          {
            'id': 'toolu_0141N6qqWnD2QUUqugswbWLJ',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_106"}',
            },
          },
          {
            'id': 'toolu_01G21K3oiZ6gmxm4oRETnanL',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_107"}',
            },
          },
          {
            'id': 'toolu_015taZ8EsE3mUFqkfjqASDRy',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_108"}',
            },
          },
          {
            'id': 'toolu_01FqEemeCCd9LsrcA7GSDynY',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_109"}',
            },
          },
          {
            'id': 'toolu_012pLBFsVm1AQMHnWVsWtETE',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_110"}',
            },
          },
          {
            'id': 'toolu_01PjjzXSC85xEFUjUNBAWYnh',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_111"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01UrHyYpdHtu7BDMJkwh2QRA',
        'content': 'synthetic_text_276',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_014RKws9xyBNCFH2qf253Xs3',
        'content': 'synthetic_text_277',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_0141N6qqWnD2QUUqugswbWLJ',
        'content': 'synthetic_text_278',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01G21K3oiZ6gmxm4oRETnanL',
        'content': 'synthetic_text_279',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_015taZ8EsE3mUFqkfjqASDRy',
        'content': 'synthetic_text_280',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01FqEemeCCd9LsrcA7GSDynY',
        'content': 'synthetic_text_281',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_012pLBFsVm1AQMHnWVsWtETE',
        'content': 'synthetic_text_282',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01PjjzXSC85xEFUjUNBAWYnh',
        'content': 'synthetic_text_283',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #10367] openai-chat::content:absent | tool_calls:3 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
  {
    'id': 10367,
    'signature': 'SIG_400',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_01GxoASH7dgnC1RGZVXzAxXe',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_112"}',
            },
          },
          {
            'id': 'toolu_013t3AbYiVviBL4ZnypvKdBz',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_113"}',
            },
          },
          {
            'id': 'toolu_01M7v1UeTBPePp8DoNMe9SNC',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_114"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01GxoASH7dgnC1RGZVXzAxXe',
        'content': 'synthetic_text_284',
        'requiresFollowUp': 0,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_013t3AbYiVviBL4ZnypvKdBz',
        'content': 'synthetic_text_285',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01M7v1UeTBPePp8DoNMe9SNC',
        'content': 'synthetic_text_286',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #10407] openai-chat::content:absent | tool_calls:4 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
  {
    'id': 10407,
    'signature': 'SIG_401',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_01DPW63JB25TybNsMxP52LtT',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_115"}',
            },
          },
          {
            'id': 'toolu_019vYpR6krxBW3DkoiY2mxGV',
            'type': 'function',
            'function': {
              'name': 'web_search',
              'arguments': '{"key":"value_116"}',
            },
          },
          {
            'id': 'toolu_01WnxEw9suuyF2HQHxQJRW1u',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_117"}',
            },
          },
          {
            'id': 'toolu_01HCgRPKfSuUv6H3sRYC6Czr',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_118"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01DPW63JB25TybNsMxP52LtT',
        'content': 'synthetic_text_287',
        'requiresFollowUp': 0,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_019vYpR6krxBW3DkoiY2mxGV',
        'content': 'synthetic_text_288',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01WnxEw9suuyF2HQHxQJRW1u',
        'content': 'synthetic_text_289',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_01HCgRPKfSuUv6H3sRYC6Czr',
        'content': 'synthetic_text_290',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #13071] openai-chat::content:string | tool_calls:3 → tool_content:string | rfu:number:0 → tool_content:string | rfu:number:1 → tool_content:string | rfu:number:1
  {
    'id': 13071,
    'signature': 'SIG_402',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_291',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01SUz4xfcLbDnA4QDZDXxYNy',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_119"}',
            },
          },
          {
            'id': 'toolu_vrtx_016uQm6ivjBXaGoP6JivxkJb',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_120"}',
            },
          },
          {
            'id': 'toolu_vrtx_01AFDvjNQ1UaREareEzEjwH9',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_121"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01SUz4xfcLbDnA4QDZDXxYNy',
        'content': 'synthetic_text_292',
        'requiresFollowUp': 0,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_016uQm6ivjBXaGoP6JivxkJb',
        'content': 'synthetic_text_293',
        'requiresFollowUp': 1,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01AFDvjNQ1UaREareEzEjwH9',
        'content': 'synthetic_text_294',
        'requiresFollowUp': 1,
      },
    ],
  },
  // [TR #14484] openai-chat::content:string | tool_calls:5 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
  {
    'id': 14484,
    'signature': 'SIG_403',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_295',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_019yDngzNQP7Z8YGQx4pFute',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_122"}',
            },
          },
          {
            'id': 'toolu_vrtx_015MJq1quaXeqG9JY1j1kJNz',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_123"}',
            },
          },
          {
            'id': 'toolu_vrtx_018pdPsVT2Y56hdoSdT2uGG7',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_124"}',
            },
          },
          {
            'id': 'toolu_vrtx_014nocQfZr1GtzELpzSVmZBT',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_125"}',
            },
          },
          {
            'id': 'toolu_vrtx_016f41FK6msUPGKz26TFT84S',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_126"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_019yDngzNQP7Z8YGQx4pFute',
        'content': 'synthetic_text_296',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_015MJq1quaXeqG9JY1j1kJNz',
        'content': 'synthetic_text_297',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_018pdPsVT2Y56hdoSdT2uGG7',
        'content': 'synthetic_text_298',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_014nocQfZr1GtzELpzSVmZBT',
        'content': 'synthetic_text_299',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_016f41FK6msUPGKz26TFT84S',
        'content': 'synthetic_text_300',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #14645] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:false
  {
    'id': 14645,
    'signature': 'SIG_404',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01YBhgv1MRdxLJPucUY7SSLS',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_127"}',
            },
          },
          {
            'id': 'toolu_vrtx_01Ppcmqu2Pq8p7Hpk5RkZLUg',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_128"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01YBhgv1MRdxLJPucUY7SSLS',
        'content': 'synthetic_text_301',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01Ppcmqu2Pq8p7Hpk5RkZLUg',
        'content': 'synthetic_text_302',
        'requiresFollowUp': false,
      },
    ],
  },
  // [TR #14650] openai-chat::content:absent | tool_calls:4 → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true → tool_content:string | rfu:boolean:true
  {
    'id': 14650,
    'signature': 'SIG_405',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01PjqftQTsRBcmuZYH8fe85B',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_129"}',
            },
          },
          {
            'id': 'toolu_vrtx_01985FQoFLtTvPUgZ9yEWPzs',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_130"}',
            },
          },
          {
            'id': 'toolu_vrtx_01BGRvMvQhQzSxCNCez2TNFS',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_131"}',
            },
          },
          {
            'id': 'toolu_vrtx_01PineVekLFt6zw2533XZ3yr',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_132"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01PjqftQTsRBcmuZYH8fe85B',
        'content': 'synthetic_text_303',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01985FQoFLtTvPUgZ9yEWPzs',
        'content': 'synthetic_text_304',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01BGRvMvQhQzSxCNCez2TNFS',
        'content': 'synthetic_text_305',
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01PineVekLFt6zw2533XZ3yr',
        'content': 'synthetic_text_306',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #14810] openai-chat::content:absent | tool_calls:2 → tool_content:string | rfu:boolean:false → tool_content:string | rfu:boolean:true
  {
    'id': 14810,
    'signature': 'SIG_406',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_013JHsYEBrpMacacwdbuFikq',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_133"}',
            },
          },
          {
            'id': 'toolu_vrtx_01Y9pAFqNCjoHX5HTHnmyzsw',
            'type': 'function',
            'function': {
              'name': 'bash',
              'arguments': '{"key":"value_134"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_013JHsYEBrpMacacwdbuFikq',
        'content': 'synthetic_text_307',
        'requiresFollowUp': false,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01Y9pAFqNCjoHX5HTHnmyzsw',
        'content': 'synthetic_text_308',
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #15775] openai-chat::content:string | tool_calls:1 | reasoning:[reasoning_content] → tool_content:string | rfu:boolean:false
  {
    'id': 15775,
    'signature': 'SIG_407',
    'data': [
      {
        'role': 'assistant',
        'reasoning_content': 'synthetic_text_320',
        'content': 'synthetic_text_309',
        'tool_calls': [
          {
            'id': 'send_message:104',
            'type': 'function',
            'function': {
              'name': 'send_message',
              'arguments': '{"key":"value_135"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'send_message:104',
        'content': 'synthetic_text_310',
        'requiresFollowUp': false,
      },
    ],
  },
  // [TR #16420] openai-chat::content:absent | tool_calls:3 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true
  {
    'id': 16420,
    'signature': 'SIG_408',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_019F4RwREYgMftrTKyDnAp2v',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_136"}',
            },
          },
          {
            'id': 'toolu_vrtx_01Ftyi5iExbjCewDQeXG8KZy',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_137"}',
            },
          },
          {
            'id': 'toolu_vrtx_011buAwbGoQ4taMQazgo4zhk',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_138"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_019F4RwREYgMftrTKyDnAp2v',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01Ftyi5iExbjCewDQeXG8KZy',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_011buAwbGoQ4taMQazgo4zhk',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #16427] openai-chat::content:absent | tool_calls:4 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true
  {
    'id': 16427,
    'signature': 'SIG_409',
    'data': [
      {
        'role': 'assistant',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01UpVCZJDksnPscS8mS3Nwz3',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_139"}',
            },
          },
          {
            'id': 'toolu_vrtx_01BSeamKg21Dk7Lnd6VNXEcm',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_140"}',
            },
          },
          {
            'id': 'toolu_vrtx_012wWvXzyvAT4f57UH4XMBWJ',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_141"}',
            },
          },
          {
            'id': 'toolu_vrtx_01QBVmUT9PNpTBPv3djc3DjJ',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_142"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01UpVCZJDksnPscS8mS3Nwz3',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01BSeamKg21Dk7Lnd6VNXEcm',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_012wWvXzyvAT4f57UH4XMBWJ',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01QBVmUT9PNpTBPv3djc3DjJ',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
    ],
  },
  // [TR #19962] openai-chat::content:string | tool_calls:2 → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true → tool_content:array | tool_blocks:[input_image] | rfu:boolean:true
  {
    'id': 19962,
    'signature': 'SIG_410',
    'data': [
      {
        'role': 'assistant',
        'content': 'synthetic_text_311',
        'tool_calls': [
          {
            'id': 'toolu_vrtx_01XoKg9opxi8GSV28ugF9DsZ',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_143"}',
            },
          },
          {
            'id': 'toolu_vrtx_01NZ3S4ubvZWpkseUMjB94zp',
            'type': 'function',
            'function': {
              'name': 'read_image',
              'arguments': '{"key":"value_144"}',
            },
          },
        ],
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01XoKg9opxi8GSV28ugF9DsZ',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
      {
        'role': 'tool',
        'tool_call_id': 'toolu_vrtx_01NZ3S4ubvZWpkseUMjB94zp',
        'content': [
          {
            'type': 'input_image',
            'image_url': 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADUlEQVR4nGNgYGBgAAAABQABpfZFQAAAAABJRU5ErkJggg==',
            'detail': 'high',
          },
        ],
        'requiresFollowUp': true,
      },
    ],
  },
];

export const responsesFixtures: Fixture<ResponsesDataItem>[] = [
  // [TR #1288] responses::content:array | blocks:[output_text] | tool_calls:none | extra:[type] → type:function_call | fc_extra:[status] → type:function_call_output | output:string | rfu:number:0
  {
    'id': 1288,
    'signature': 'SIG_411',
    'data': [
      {
        'type': 'message',
        'role': 'assistant',
        'content': [
          {
            'type': 'output_text',
            'text': 'synthetic_text_312',
          },
        ],
      },
      {
        'type': 'function_call',
        'call_id': 'toolu_bdrk_01DH4pwrufMrXcymPDKMnFBS',
        'name': 'send_message',
        'arguments': '{"key":"value_145"}',
        'status': 'completed',
      },
      {
        'type': 'function_call_output',
        'call_id': 'toolu_bdrk_01DH4pwrufMrXcymPDKMnFBS',
        'output': '{"key":"value_336"}',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #1176] responses::type:function_call | fc_extra:[id,status] → type:function_call_output | output:string | rfu:number:0
  {
    'id': 1176,
    'signature': 'SIG_412',
    'data': [
      {
        'arguments': '{"key":"value_146"}',
        'call_id': 'call_Pj8NSw6VJj7f1eGKbrdvjRfc',
        'id': '26e8+mo9tDZkiOzTJzK+qH+oaz45N6Lz9x5ZBLiAKBdM2qBEBWnEnaVfDs3looQ7tR4T0gAmLDDrLLsz2sS7gvaRCAylrGOSCDmhzaDGpkglTzkrh53Enj+ENCwo0feF+vZf/+kq3eu6BaYFlFFDbL5+uHvZhaxXWJXfIjzslUJ9YnedJvgb6GHsnZOvkYbjDJerUXD7...TRUNCATED...NirKN0Eq1Y2uIgnnxD1xxvttCQe/O8bdClotGLgqm/U9aT8w==',
        'name': 'send_message',
        'status': 'completed',
        'type': 'function_call',
      },
      {
        'type': 'function_call_output',
        'call_id': 'call_Pj8NSw6VJj7f1eGKbrdvjRfc',
        'output': '{"key":"value_337"}',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #1316] responses::
  {
    'id': 1316,
    'signature': 'SIG_413',
    'data': [],
  },
  // [TR #1282] responses::content:array | blocks:[output_text] | tool_calls:none | extra:[type]
  {
    'id': 1282,
    'signature': 'SIG_414',
    'data': [
      {
        'type': 'message',
        'role': 'assistant',
        'content': [
          {
            'type': 'output_text',
            'text': 'synthetic_text_313',
          },
        ],
      },
    ],
  },
  // [TR #1283] responses::type:function_call | fc_extra:[status] → type:function_call_output | output:string | rfu:number:0
  {
    'id': 1283,
    'signature': 'SIG_415',
    'data': [
      {
        'type': 'function_call',
        'call_id': 'toolu_bdrk_016VWhpvMC1ugdhEUFr6KHiC',
        'name': 'send_message',
        'arguments': '{"key":"value_147"}',
        'status': 'completed',
      },
      {
        'type': 'function_call_output',
        'call_id': 'toolu_bdrk_016VWhpvMC1ugdhEUFr6KHiC',
        'output': '{"key":"value_338"}',
        'requiresFollowUp': 0,
      },
    ],
  },
  // [TR #1197] responses::content:array | blocks:[output_text] | tool_calls:none | extra:[id,phase,status,type] → type:function_call | fc_extra:[id,status] → type:function_call_output | output:string | rfu:number:0
  {
    'id': 1197,
    'signature': 'SIG_416',
    'data': [
      {
        'content': [
          {
            'annotations': [],
            'logprobs': [],
            'text': '',
            'type': 'output_text',
          },
        ],
        'id': '5kfUBU/MSQ978/YDk74tyfKOkY6VIR2uJEVhifV65CskmNNVR4vGvRHNVZ9ybVpvinxWc5SSt8BZryZW30xl6JljQtKaNIlzMhOuL6NONWLPl0bTmtEt6xE2rSxVGqptPbUNtv7ox1Uy02zBybIms0wu79dPgGoKuRYArAhTyoKukMoJrvhVeNN5z7loFRyQfsFW5P1l...TRUNCATED...Pj3cCCjJToiDMhrAFy2U0sd2PkkBjGpJs21n5qOBknF4gQWHU=',
        'phase': 'commentary',
        'role': 'assistant',
        'status': 'completed',
        'type': 'message',
      },
      {
        'arguments': '{"key":"value_148"}',
        'call_id': 'call_UyaVfJCZfffRel6wZxELExqQ',
        'id': 'RndwbHL+bhFvg0apogwHtoyKSoQOEtm7W/mlcLfsMYHGKEqpDSmsJeX/s5TprcSmYJrqzEUr9SiQTJFOmX+Z1tsg6PAJ8+SqensYmVNJldNGGoESPOIWzUUQI5Mxd/T99leSlKFtJ6RF/Rr6TlM1bsn8dTrymeqfzBhDUQbVGv2nDPrHv8xorrnsl3UYnXPeONKeqQti...TRUNCATED...s4qmFrx5eat3jB9ZKx6hSEWdz5e5q2+tFlQSqxbSZTj+UTgg==',
        'name': 'send_message',
        'status': 'completed',
        'type': 'function_call',
      },
      {
        'type': 'function_call_output',
        'call_id': 'call_UyaVfJCZfffRel6wZxELExqQ',
        'output': '{"key":"value_339"}',
        'requiresFollowUp': 0,
      },
    ],
  },
];
